### ISSUE TITLE
object with keys

### ISSUE THREAD

**Issue by guilhermesachinelli** [thiago-rferreira/duvidas#12]
![Captura de tela 2023-09-21 093642](https://github.com/thiago-rferreira/duvidas/assets/124887055/efa2a8da-1011-4816-91e3-4a5e535be633)
![Captura de tela 2023-09-21 093702](https://github.com/thiago-rferreira/duvidas/assets/124887055/50eecb5f-2e62-45cf-826c-328cc1f1780f)

**Comment by FelipeSantos92Dev** [comment]
Coloque as props entre chaves: "{}"
