### ISSUE TITLE
erro desconhecido

### ISSUE THREAD

**Issue by Rnchx** [thiago-rferreira/duvidas#13]
![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/7c2dcef3-ea92-4932-92a6-73ea34815ad3)

**Comment by FelipeSantos92Dev** [comment]
padraoContador é uma variável que necessita ser declarada antes de ser usada.

**Comment by Rnchx** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/6f8c0b30-7f81-45e9-9f58-6aa4feb695b7)

outro erro

código:

![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/8d586822-854f-4bee-a192-3f12456d7820)

**Comment by FelipeSantos92Dev** [comment]
#12 Resolvido aqui
