### ISSUE TITLE
Erro .map

### ISSUE THREAD

**Issue by andreyfdecastro** [thiago-rferreira/duvidas#14]
meu jsx não esta lendo o .map

![image](https://github.com/thiago-rferreira/duvidas/assets/124887041/46d219b2-323e-42d8-abd4-ae1103f7c117)
![image](https://github.com/thiago-rferreira/duvidas/assets/124887041/7d6caba1-eb48-4705-a439-3586aa2454d6)

**Comment by thiago-rferreira** [comment]
Provavelmente seu array esta com o nome diferente! Consegue me mostrar um print do nome do array?

**Comment by andreyfdecastro** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/124887041/f79a1f2f-7cc9-4b08-acab-995f5e72f155)

**Comment by thiago-rferreira** [comment]
consola o array e veja se ele esta sendo preenchido.
O erro ali diz que o map nao recebe itens vazios. Ou seja, seu array esta vazio.

Faça esses testes pf

**Comment by thiago-rferreira** [comment]
Vi o erro.
<img width="715" alt="image" src="https://github.com/thiago-rferreira/duvidas/assets/124102245/e10536c7-c604-417e-ba91-fae211dfcbd5">

Faltou o useState.
