### ISSUE TITLE
Erro de caminho

### ISSUE THREAD

**Issue by PedrooSantoss** [thiago-rferreira/duvidas#15]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502040/abb3463c-6d49-4a0e-8376-70efc81d004c)

Está dando erro 404, preciso de ajuda com o link, ja tentei de varios jeitos e não consegui

**Comment by FelipeSantos92Dev** [comment]
Envie um print com a pasta de arquivos aberta no VS Code.

**Comment by PedrooSantoss** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502040/1ff8e124-f849-47a4-af40-bc30bbbcb9a5)
![Uploading image.png…]()
das duas páginas

**Comment by thiago-rferreira** [comment]
coloque o nome da rota como page.jsx

**Comment by PedrooSantoss** [comment]
continua o erro 404

**Comment by thiago-rferreira** [comment]
a pasta esta na hierarquia errada.
