### ISSUE TITLE
Erro - Each child in a list should have a unique key prop

### ISSUE THREAD

**Issue by Rnchx** [thiago-rferreira/duvidas#16]
![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/54c7a8bd-341b-4025-8331-4436ebfed5e5)

Task quando criada, renderiza vazia!

**Comment by thiago-rferreira** [comment]
Está faltando colocar a key no map.

**Comment by Rnchx** [comment]
Coloquei a key no map e o erro persiste:


![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/2b64625f-4ccb-42f6-81b0-2d5990fc3241)

**Comment by thiago-rferreira** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/124102245/bff3024c-81a3-4bb5-baaa-e0201cc7b080)

A ordem está invertida. 
Primeiro task e depois index.

**Comment by Rnchx** [comment]
ainda sim persiste:

![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/d92cb7c0-9c8c-4577-8795-402daed73435)


![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/5844d86f-ddfe-43af-a560-d32938264766)

**Comment by thiago-rferreira** [comment]
Tira as chaves do map
