### ISSUE TITLE
O taskList não está definido!

### ISSUE THREAD

**Issue by analiviamartins** [thiago-rferreira/duvidas#17]
Eu fiz errado?

![image](https://github.com/thiago-rferreira/duvidas/assets/124887131/62de4d6c-50c0-4c92-98de-0cc6ed2423ae)
![image](https://github.com/thiago-rferreira/duvidas/assets/124887131/6f5fc369-7b07-4e8c-bda3-3897d41594f8)

**Comment by thiago-rferreira** [comment]
cade a declaração da variavel taskList?
