### ISSUE TITLE
Erro desconhecido.

### ISSUE THREAD

**Issue by liviaxsouza** [thiago-rferreira/duvidas#18]
Eu não faço a menor ideia do que significa esse erro:
![issue](https://github.com/thiago-rferreira/duvidas/assets/123502021/56590655-da84-47ca-89f2-cd9f510e28d3)

**Comment by thiago-rferreira** [comment]
cade o código?

**Comment by thiago-rferreira** [comment]
Olha a #12 e vc achará sua resposta!
