### ISSUE TITLE
Erro no use Client

### ISSUE THREAD

**Issue by PedrooSantoss** [thiago-rferreira/duvidas#20]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502040/1a111792-fda6-48c9-b0fd-ae1f3353bad6)
Preciso de ajuda, não sei como arrumar esse erro, já entreguei só q sem a print da tela, Guilherme me ajudou com o código

**Comment by thiago-rferreira** [comment]
"use client" com letras minúsculas.
