### ISSUE TITLE
como colocar 2 estilos/ duas classes de CSS

### ISSUE THREAD

**Issue by pedromonteir01** [thiago-rferreira/duvidas#21]
![image](https://github.com/thiago-rferreira/duvidas/assets/123501825/9d24821f-f602-441e-bafe-f892ed99c792)

**Comment by thiago-rferreira** [comment]
Assim:

<img width="760" alt="image" src="https://github.com/thiago-rferreira/duvidas/assets/124102245/eae73e2e-21aa-434b-93f6-6ed84ef5e622">
