### ISSUE TITLE
Como coloca um prop na class name

### ISSUE THREAD

**Issue by CaioCicca** [thiago-rferreira/duvidas#25]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502294/ff8a5b64-3242-4351-846c-600ffec04468)

**Comment by thiago-rferreira** [comment]
Voce pode colocar o style dentro de uma variavel e depois colocar a variavel na className. 
Ou colocar direto a props no className.

<img width="396" alt="image" src="https://github.com/thiago-rferreira/duvidas/assets/124102245/4eb24aaf-00d1-473f-b47f-eca2c79fb413">

E ter ctz que essa class existe no css.

Se nao funcionar tente assim:

<img width="787" alt="image" src="https://github.com/thiago-rferreira/duvidas/assets/124102245/450018fe-468a-447d-b2b7-b648de08dffd">

e depois

<img width="298" alt="image" src="https://github.com/thiago-rferreira/duvidas/assets/124102245/66c99c07-4292-49c0-b853-314ffa5c8845">
