### ISSUE TITLE
Não sei pq o meu css n vai

### ISSUE THREAD

**Issue by Amandamoonchild** [thiago-rferreira/duvidas#27]
pq eu n posso fazer isso?
![image](https://github.com/thiago-rferreira/duvidas/assets/123501998/097f7ca3-e262-4f27-a9f6-7fda54d2e6cf)

no caso, eu estaria chamando o nome da class pelo parametro

**Comment by FelipeSantos92Dev** [comment]
Veja se ajuda: #25

**Comment by Amandamoonchild** [comment]
> Veja se ajuda: #25

professor, eu de verdade nao entendi nada e to perdida
