### ISSUE TITLE
Erro: Cannot destructure property 'message' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by liviaxsouza** [thiago-rferreira/duvidas#28]
Não sei o que está dando de errado, tenho certeza que minha lógica não está certa mas não sei como fazer.

![image](https://github.com/thiago-rferreira/duvidas/assets/123502021/60578afe-969a-4cc4-b353-7dcf912502c1)
![code](https://github.com/thiago-rferreira/duvidas/assets/123502021/53c0fdd8-6af5-4567-a974-5a45c8849c7a)
![code2](https://github.com/thiago-rferreira/duvidas/assets/123502021/427ef478-cdec-4ec6-9672-6426ce8d22bc)

**Comment by thiago-rferreira** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/124102245/516957ae-9989-463f-86d7-b46e4378b362)

`Troca que por message = {'Mensagem'} e a mesma coisa para o tipo.`

**Comment by thiago-rferreira** [comment]
Feito em conjunto.
