### ISSUE TITLE
Lógica de exibição do Pop Up

### ISSUE THREAD

**Issue by Alineevang** [thiago-rferreira/duvidas#29]
<img width="410" alt="popUp" src="https://github.com/thiago-rferreira/duvidas/assets/123502100/456f55da-10fd-47a1-bab1-283212c1246e">

<img width="377" alt="popUpexibir" src="https://github.com/thiago-rferreira/duvidas/assets/123502100/3f389a5c-7502-4125-afb2-f8a1d0c9f153">

Por favor, me dizem se eu estou no caminho certo. Depois disso eu não sei muito como prosseguir mas, sei que a lógica da Task List está relacionada com isso na hora da exibição.

**Comment by thiago-rferreira** [comment]
Feito em conjunto.
