### ISSUE TITLE
erro de sintaxe

### ISSUE THREAD

**Issue by PedrooSantoss** [thiago-rferreira/duvidas#3]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502040/42dfad50-e9a8-4e0d-b7a4-33d5cf90f3d9)

Erro na linha 24 no parênteses

**Comment by thiago-rferreira** [comment]
const reset = () **=>** {
        setContador(0);
    }


Faltou a arrow

**Comment by PedrooSantoss** [comment]
> const reset = () **=>** { setContador(0); }
> 
> Faltou a arrow

**Comment by PedrooSantoss** [comment]
Deu certo, obrigado.
