### ISSUE TITLE
O que é o UseEffect?

### ISSUE THREAD

**Issue by JuliaFee** [thiago-rferreira/duvidas#30]
Pesquisei como funcionaria o setTimeout com JSX na internet para ver se tinha alguma sintaxe diferente, e todos os sites mencionam o UseEffect. O que seria? É necessário usar?

**Comment by FelipeSantos92Dev** [comment]
Ainda teremos aula sobre o assunto. Basicamente ele é executado quando o estado de alguma variável muda.
