### ISSUE TITLE
meu css nao esta pegando no codigo

### ISSUE THREAD

**Issue by CaioCicca** [thiago-rferreira/duvidas#32]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502294/e1da5964-8be3-4e84-ac2e-f3565464bb76)
![image](https://github.com/thiago-rferreira/duvidas/assets/123502294/b48f339b-5a75-44af-a3e0-96f9857e6ab6)
![Uploading image.png…]()

**Comment by CaioCicca** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502294/712a8886-b5a9-4788-8b86-2741389e7579)

**Comment by thiago-rferreira** [comment]
moddule com dois d
