### ISSUE TITLE
Erro Desconhecido ao criar If-ternário

### ISSUE THREAD

**Issue by Rnchx** [thiago-rferreira/duvidas#34]
![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/4af8a6b4-c011-4e0c-9927-d79b68d0cc2c)

![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/30718607-ecc2-4f43-a2a6-f19346ee6a4b)

**Comment by thiago-rferreira** [comment]
`var color = (type === 'success') ? styles.success : styles.error;`
