### ISSUE TITLE
Problema no link - map is not a function

### ISSUE THREAD

**Issue by pedromonteir01** [thiago-rferreira/duvidas#36]
![image](https://github.com/thiago-rferreira/duvidas/assets/123501825/4be74c1c-1f1b-4b25-b152-dc01015e6d04)
![image](https://github.com/thiago-rferreira/duvidas/assets/123501825/f83a21ab-a364-43c0-9ecc-cadf61156672)

**Comment by thiago-rferreira** [comment]
Apaga a extensão .js

**Comment by thiago-rferreira** [comment]
Voce exportou o cars dentro de data?

**Comment by pedromonteir01** [comment]
não, irei exportar
