### ISSUE TITLE
Meu código não exibe

### ISSUE THREAD

**Issue by JuliaFee** [thiago-rferreira/duvidas#37]
Não sei o que há de errado com o caminho do JS, tentei escrever como 'data/carros.js', sem sucesso, fiz o caminho manualmente, mesmo assim sem sucesso
![image](https://github.com/thiago-rferreira/duvidas/assets/123502211/560ce483-fa0f-4ccf-a50b-2a5a3367956f)
![image](https://github.com/thiago-rferreira/duvidas/assets/123502211/130c4875-0579-46b2-9db0-d99016a7b0fd)
![image](https://github.com/thiago-rferreira/duvidas/assets/123502211/d5c0885c-84a9-4849-9936-8edef7e9a93e)
![image](https://github.com/thiago-rferreira/duvidas/assets/123502211/36423bf4-66c0-407b-bda5-48e1de18d818)
![image](https://github.com/thiago-rferreira/duvidas/assets/123502211/a55cfbbe-8b8d-49c2-9618-a471caf5aee4)

**Comment by thiago-rferreira** [comment]
Voce está usando o objeto no plural e exibindo ele como singular.

Deixe data/carros no import mesmo.
