### ISSUE TITLE
Ajuda nesse erro

### ISSUE THREAD

**Issue by miottofelipee** [thiago-rferreira/duvidas#38]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502192/fdb4097f-44f1-481b-82f9-41c787928fc7)

**Comment by JuliaFee** [comment]
Precisa fechar em chaves {} para realizar o javascript num HTML

**Comment by JuliaFee** [comment]
Assim: { carros.map((carro) => (
[exemplo]
) ) }
