### ISSUE TITLE
erro no export

### ISSUE THREAD

**Issue by PedrooSantoss** [thiago-rferreira/duvidas#39]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502040/b9786ef8-bf2e-418f-918b-9f82c217fe78)
minha sintaxe aparentemente está correta
no codigo nao aparece nenhum erro

**Comment by thiago-rferreira** [comment]
Voce apagou ou a layout ou a pages na raiz

**Comment by PedrooSantoss** [comment]
obrigado
