### ISSUE TITLE
Erro Map - Itens nao aparece na tela

### ISSUE THREAD

**Issue by Amandamoonchild** [thiago-rferreira/duvidas#41]
Meu código ta assim

![image](https://github.com/thiago-rferreira/duvidas/assets/123501998/b51bc4d6-baa1-463c-ba0f-8d38dfe38d49)

mas na tela tá assim:

![image](https://github.com/thiago-rferreira/duvidas/assets/123501998/78fa1cf9-7a9f-4da8-8249-6fc7441ff56f)

**Comment by thiago-rferreira** [comment]
A importacao esta errada.

**Comment by Amandamoonchild** [comment]
Erro: No map, usei {} no lugar de ()
![image](https://github.com/thiago-rferreira/duvidas/assets/123501998/330e0e74-0a12-4150-a440-d4f659ce80bb)

solução: substituir por ()
![image](https://github.com/thiago-rferreira/duvidas/assets/123501998/fa857940-a61b-400f-8bf4-fe5fdfb0012f)

**Comment by thiago-rferreira** [comment]
Boa@!
