### ISSUE TITLE
Erro na instância - is not a constructor

### ISSUE THREAD

**Issue by Rnchx** [thiago-rferreira/duvidas#43]
![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/470440be-1562-4bae-9699-289c17ecd36c)

![image](https://github.com/thiago-rferreira/duvidas/assets/123501793/f5d41fcd-fcea-43b3-be81-f0817c351e4d)

**Comment by thiago-rferreira** [comment]
Verifica esse ../ nao esta te tirando da raiz

**Comment by Rnchx** [comment]
PARA RESOLVER:

verifique todos os seus Exports em sua Rota:

---------------------------------------------------------------------------------------------------------------------------------------------

se estiver: export default [nome da class / function]
deve escrever na sua rota: import [nome da class / function] from 'caminho'

---------------------------------------------------------------------------------------------------------------------------------------------

se estiver: export class [nome da class / function] ,
deve escrever na sua rota: import {nome da class / function} from 'caminho'

**Comment by thiago-rferreira** [comment]
Toop
