### ISSUE TITLE
Erro no método da instância

### ISSUE THREAD

**Issue by liviaxsouza** [thiago-rferreira/duvidas#45]
Não sei o que eu fiz de errado
![image](https://github.com/thiago-rferreira/duvidas/assets/123502021/33742718-c140-4e96-80bc-73201924b205)
![code-cars3](https://github.com/thiago-rferreira/duvidas/assets/123502021/7271d5ab-2367-4cdc-be66-c46bbdfa9fef)
![code-cars4](https://github.com/thiago-rferreira/duvidas/assets/123502021/3e446fee-f7aa-4875-a98c-dd0d31586a2b)

**Comment by thiago-rferreira** [comment]
nome errado.
