### ISSUE TITLE
Correção do erro de dupla requisição da API

### ISSUE THREAD

**Issue by CaioCicca** [thiago-rferreira/duvidas#46]
Este erro acontece pois a API é chamada duas vezes para garantir que não há quebra no documento JSON.

Correção do erro:
![image](https://github.com/thiago-rferreira/duvidas/assets/123502294/146cce8d-8a0b-42f8-be7c-d09386ac6e62)
link do site onde retirei a solução: https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development

Aplicação da solução no meu código:
![image](https://github.com/thiago-rferreira/duvidas/assets/123502294/3792219b-e3c9-488c-9a4c-5ac6823dad91)

**Comment by thiago-rferreira** [comment]
ok
