### ISSUE TITLE
Problema 

### ISSUE THREAD

**Issue by lmcomito** [thiago-rferreira/duvidas#5]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502182/be1471f3-b7e3-4eab-9a86-8677bbbdb352)

Alguém me ajuda a resolver?                                                                                                                                                                                Grata.

**Comment by FelipeSantos92Dev** [comment]
Imagem ilegível.

**Comment by FelipeSantos92Dev** [comment]
Na linha 10 você adicionou o caractere "=". Como a variável contador é uma const, reatribuir um valor a uma constante não é permitido.

**Comment by lmcomito** [comment]
> Na linha 10 você adicionou o caractere "=". Como a variável contador é uma const, reatribuir um valor a uma constante não é permitido.

Eu deitei o erro agora @FelipeSantos92Dev
