### ISSUE TITLE
Como fazer os verificadores

### ISSUE THREAD

**Issue by pedromonteir01** [thiago-rferreira/duvidas#6]
Máximo e mínimo
<img width="394" alt="Screenshot_5" src="https://github.com/thiago-rferreira/duvidas/assets/123501825/65b3c43d-1e81-4fbe-bd1c-ae7e7e4e3813">

**Comment by thiago-rferreira** [comment]
Faz uma cadeia de if normal

**Comment by pedromonteir01** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/123501825/ca6a37cf-3518-4ce6-81dd-1508666b8136)
help!!

**Comment by thiago-rferreira** [comment]
cade o código atualizado?

**Comment by pedromonteir01** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/123501825/cccb2eee-1527-4636-ab46-3c8ce7edeb10)

**Comment by thiago-rferreira** [comment]
Na declaracao das propos use { }
