### ISSUE TITLE
Erro de Sintaxe 

### ISSUE THREAD

**Issue by LuFassini** [thiago-rferreira/duvidas#8]
Chave da function linha 7 e parenteses.
![image](https://github.com/thiago-rferreira/duvidas/assets/123502647/05cf06b6-421b-49de-b87d-a3db3e48f520)
![image](https://github.com/thiago-rferreira/duvidas/assets/123502647/ebb1d299-19e3-45ab-b629-ca46b4e8d8d8)

**Comment by FelipeSantos92Dev** [comment]
Primeiramente, a importação do react é "useState". Você importou e usou "userState".
No próximo print do código, mostre também as linhas, por favor!

**Comment by LuFassini** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502647/d9c050f7-7d6d-4940-8f82-dfb18081609a)

**Comment by thiago-rferreira** [comment]
soluçao acima!
