### ISSUE TITLE
Não entendi o que é para fazer.

### ISSUE THREAD

**Issue by JuliaFee** [thiago-rferreira/duvidas#9]
Não entendi o que é pra fazer, é isso?
![image](https://github.com/thiago-rferreira/duvidas/assets/123502211/e8c2b391-ac52-4c22-a116-54711c6e2fcb)

**Comment by FelipeSantos92Dev** [comment]
Primeiramente a variável valorPadrao não foi definida no momento que é chamada.

**Comment by JuliaFee** [comment]
> Primeiramente a variável valorPadrao não foi definida no momento que é chamada.

Mas não seria isso? Pra pessoa que pegar o código definir?

**Comment by JuliaFee** [comment]
![image](https://github.com/thiago-rferreira/duvidas/assets/123502211/f91a4d14-c1e4-4c09-808b-b67301c45d10)
![image](https://github.com/thiago-rferreira/duvidas/assets/123502211/c3f37a60-6af8-4fc4-8aaf-fa76ac0099bf)
Desculpa,  eu genuinamente não entendi o que é para fazer, muito menos esse erro que está dando.
![image](https://github.com/thiago-rferreira/duvidas/assets/123502211/8cc8bf76-9add-43a0-bc1e-4fef6d0daf4a)

**Comment by FelipeSantos92Dev** [comment]
Envolva todas as props com chaves "{}".
